Darkmode
QuiiBz/next-international pull request #243
Opened 2023-10-13 15:08 UTC by Willem-Jaap

Nextra has a nice built-in darkmode, this pr enables it along with some small fixes

- feat: enable darkMode
- fix: update svg regex to match actual pattern in imports file
- feat: add logo component with darkmode support, fix import and formatting

2023-10-13 15:21 UTC, Willem-Jaap commented
I upgraded deps, looks like that breaks linting, I'll take a look when I have the time

2023-10-14 09:04 UTC, QuiiBz requested changes
Thanks for the PR! Some suggestions:

2023-10-14 09:04 UTC, QuiiBz commented on pnpm-lock.yaml
Can you revert the dependencies upgrade? In both `docs/package.json` & `pnpm-lock.yaml`

2023-10-14 09:04 UTC, QuiiBz commented on docs/pages/index.mdx
> +
Extra line not needed

2023-10-14 13:31 UTC, QuiiBz approved these changes
LGTM!

2023-10-14 13:31 UTC, merged