chore(docs): add rtl support (#220)
QuiiBz/next-international pull request #273
Opened 2023-10-29 19:38 UTC by gustaveWPM

Hello.
I've added a documentation page about RTL support, as we previously discussed here: https://github.com/QuiiBz/next-international/issues/220

I've documented two possible implementations.
However, the second, proposing an implementation based on a _useEffect_ call, seems to be a bad choice, after some rethinking.

I've written the documentation for it anyway in this PR, but I think we should remove it because of the point I mentioned in "Caveat".
> Note that this choice of implementation will cause an UI flickering when your user loads your web pages for the first time.  
> This is because the page will first be mounted with the default `dir` attribute value of your HTML node, then updates when the component including the `useEffect` is mounted. This will introduce CLS (Cumulative Layout Shift) issues.

As a reminder, we thought this might be a good idea here:
- https://github.com/QuiiBz/next-international/issues/220#issuecomment-1777353924
- https://github.com/QuiiBz/next-international/issues/220#issuecomment-1777593721

Thanks in advance for your review and for your feedback.

2023-10-29 19:47 UTC, gustaveWPM commented
I had to proofread my contribution several times and refine it a little.
I think I'm OK on my side for a review.

2023-10-30 08:09 UTC, QuiiBz requested changes
Thanks! Here are a few suggestions, mostly about the code examples:

2023-10-30 08:09 UTC, QuiiBz commented on docs/pages/docs/rtl-support.mdx
We'll have to register this page inside `pages/docs/_meta.json` - I'm thinking about placing it just after the "Writing locales" page, with the title being "RTL support"

2023-10-30 08:09 UTC, QuiiBz commented on docs/pages/docs/rtl-support.mdx
> +In case you want the `dir` attribute of your HTML node to adjust based on the current locale, you'll need to add some logic.
```suggestion
# RTL support

If you want to support the `dir` attribute in your `<html>` tag, you'll need to add some logic:
```

2023-10-30 08:09 UTC, QuiiBz commented on docs/pages/docs/rtl-support.mdx
> +};
We usually try to remove any excessive markup to make it easier to read (so remove any `;`):
```suggestion
// app/[locale]/layout.tsx
export default function Layout({ children, params: { locale } }: { children: ReactElement, params: { locale: string } }) => {
  const dir = new Intl.Locale(locale).getTextInfo().direction

  return (
    <html lang={locale} dir={dir}>
      <body>
        {children}
      </body>
    </html>
  )
}
```

2023-10-30 08:09 UTC, QuiiBz commented on docs/pages/docs/rtl-support.mdx
> +};
Same here:
```suggestion
// app/[locale]/layout.tsx
import Locale from 'intl-locale-textinfo-polyfill'

export default function Layout({ children, params: { locale } }: { children: ReactElement, params: { locale: string } }) => {
  const { direction: dir } = new Locale(locale).textInfo;

  return (
    <html lang={locale} dir={dir}>
      <body>
        {children}
      </body>
    </html>
  )
}
```

2023-10-30 08:09 UTC, QuiiBz commented on docs/pages/docs/rtl-support.mdx
> +export default LanguageSwitcher;
```suggestion
'use client'

import { useChangeLocale, useCurrentLocale } from '../../locales/client'
import { FunctionComponent, useEffect } from 'react'

export default function LanguageSwitcher() {
  const currentLocale = useCurrentLocale()
  const changeLocale = useChangeLocale()

  useEffect(() => {
    document.documentElement.dir = isLocaleRTL(currentLocale) ? 'rtl' : 'ltr'
  }, [currentLocale])

  return (
    <div className="flex flex-col gap-4">
      <button onClick={() => changeLocale('en')}>EN</Button>
      <button onClick={() => changeLocale('fr')}>FR</Button>
    </div>
  )
}
```

2023-10-30 08:56 UTC, gustaveWPM commented on docs/pages/docs/rtl-support.mdx
Fixed here: https://github.com/QuiiBz/next-international/pull/273/commits/f1904e567aece27c057ace04b06a41d7dad3a0fd

2023-10-30 08:59 UTC, gustaveWPM commented on docs/pages/docs/rtl-support.mdx
> +};
Commited suggestion. :)
Thank you

2023-10-30 09:07 UTC, gustaveWPM commented on docs/pages/docs/rtl-support.mdx
> +export default LanguageSwitcher;
Commited suggestion. :)
Thank you

2023-10-31 08:13 UTC, QuiiBz approved these changes
Thanks a lot!

2023-10-31 08:14 UTC, merged