fix: next@15
QuiiBz/next-international pull request #426
Opened 2024-10-22 01:18 UTC by blechatellier

This PR updates `next-international` to support async changes in `next@15`.

2024-10-22 01:21 UTC, blechatellier commented
@QuiiBz hey, would appreciate a review when available to be able to upgrade to next@15

2024-10-22 13:08 UTC, fstodulski commented
☝️ I there a possibility to merge it ASAP?

2024-10-25 22:44 UTC, QuiiBz requested changes
Thanks for the PR and sorry for the delay, I'm travelling away for a few days.

Since Next.js 15 contains several breaking changes to dynamic APIs and `next-international`'s v2 version is still [wip](https://github.com/QuiiBz/next-international/pull/361) (I'm planning to work on it soon), we need to support both Next.js 14 and 15 on `next-international@1.x.x`. It might already just work with those changes in both versions given JavaScript allows non-promise values to be `await`'ed, but we need to double-check.

I left a comment for the `next-app` example that is currently broken, and the documentation also needs to be updated. I'll be able to do it on Monday once I'm back home, but feel free to update the PR before if you can so we can support Next.js 15 asap.

2024-10-25 22:44 UTC, QuiiBz commented on examples/next-app/package.json
This example needs to be updated, as the page is accessing `params.locale` without `await`ing it.

2024-10-27 21:12 UTC, blechatellier commented
@QuiiBz thanks, I've updated the docs and example.

2024-10-28 18:02 UTC, QuiiBz approved these changes
Updated the docs to still show how to use next-international with Next.js < 15, but the default will be with the new `await`able APIs.

I'm releasing `next-international@1.3.0` shortly after merging this PR, thanks!

2024-10-28 18:02 UTC, merged

2024-10-28 22:37 UTC, blechatellier commented
Thanks @QuiiBz

2024-10-29 22:30 UTC, mxzinke commented
@QuiiBz @blechatellier 

Did you miss the type safety for `getCurrentLocale`, since this now returns a promise?